# Generated by Django 5.0 on 2023-12-15 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRDIP', '0002_remove_company_root_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
