# Generated by Django 5.0 on 2023-12-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRDIP', '0003_alter_userrole_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
