# Generated by Django 5.0 on 2023-12-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRDIP', '0005_road_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='selected_model',
            field=models.IntegerField(choices=[(0, 'Swin'), (1, 'WSPLIN-IP'), (2, 'WSPLIN-SS'), (3, 'PicT')], default=0),
        ),
    ]
