# Generated by Django 5.0 on 2023-12-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRDIP', '0006_userrole_selected_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecord',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRDIP.userrole'),
        ),
    ]
