## 使用官方 MinIO 镜像作为基础镜像
#FROM minio/minio
#
## （可选）安装你需要的额外工具
## RUN apt-get update && apt-get install -y curl vim
#
## （可选）复制一些配置文件或脚本到容器中
## COPY ./my-custom-config /etc/minio/config
#
## （可选）设置工作目录
## WORKDIR /data
#
## 启动命令仍然是启动 MinIO 服务
#CMD ["server", "/data"]
